name: complex-workflow

on: push

jobs:
    ubuntu:
        runs-on: ubuntu-latest
        steps: 
        - name: ubuntu-step
          run: date
    windows:
        runs-on: windows-latest
        steps:
        - name: win-step
          run: Get-Date
    macos:
        runs-on: macos-latest
        steps: 
        - name: macos-step
          run: date
    depends:
        name: Job4
        runs-on: ubuntu-latest
        needs: [ubuntu, windows, macos]
        steps: 
        - name: depend-step
          run: date +"%d-%m-%y"
